apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-exporter.exporterDeploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mongodb-exporter.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
      {{- if .Values.exporterNamespaceName }}
      {{- include "mongodb-exporter.sysdigAnnotations" . | nindent 8 }}
      {{ else }}
      {{- include "mongodb-exporter.prometheusAnnotations" . | nindent 8 }}
      {{- end }}
      {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mongodb-exporter.selectorLabels" . | nindent 8 }}
    spec:
      affinity: {}
      containers:
      - name: mongodb-exporter
        {{- if not .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- end }}
        {{- if .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-ubi"
        {{- end }}   
        args:
        - --web.listen-address={{ printf ":%s" .Values.port }}
        - --collect.collection
        - --collect.database
        - --collect.indexusage
        - --collect.topmetrics
        - --collect.connpoolstats
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: {{ include "prometheus-mongodb-exporter.secretName" . }}
                key: {{ .Values.existingSecretKey }}
        {{- if .Values.env }}
        {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{- end }}
        {{- end }}
        {{- if or ( .Values.sslmode ) ( .Values.tlsmode ) }}
        volumeMounts:
        - name: mongodb-exporter-key
          mountPath: /etc/mongodb/mongodb-exporter-key.pem
          subPath: mongodb-exporter-key.pem
        - name: mongodb-exporter-ca
          mountPath: /etc/mongodb/mongodb-exporter-ca.pem
          subPath: mongodb-exporter-ca.pem
        {{- end }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        ports:
        - name: metrics
          containerPort: {{ .Values.port }}
          protocol: TCP
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
      {{- if or ( .Values.sslmode ) ( .Values.tlsmode )}}
      - secret:
          defaultMode: 420
          secretName: mongodb-exporter-auth
          items: 
            - key: mongodb-key
              path: mongodb-exporter-key.pem 
        name: mongodb-exporter-key
      - secret:
          defaultMode: 420
          secretName: mongodb-exporter-auth
          items: 
            - key: mongodb-ca
              path: mongodb-exporter-ca.pem 
        name: mongodb-exporter-ca
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
