spec:
  template:
    metadata:
      annotations:
      {{- if .Values.integrationType }}
      {{- include "nginx-exporter.sysdigAnnotations" . | nindent 8 }}
      {{ else }}
      {{- include "nginx-exporter.prometheusAnnotations" . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: nginx-exporter
        {{- if not .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- end }}
        {{- if .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-ubi"
        {{- end }}
        args:
          - "-nginx.scrape-uri={{ .Values.scrape.protocol }}://{{ .Values.scrape.host }}:{{ .Values.scrape.port }}{{ .Values.scrape.path }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.port }}
