apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql-exporter.exporterDeploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mysql-exporter.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
      {{- if .Values.sysdig.namespaceName }}
      {{- include "mysql-exporter.sysdigAnnotations" . | nindent 8 }}
      {{ else }}
      {{- include "mysql-exporter.prometheusAnnotations" . | nindent 8 }}
      {{- end }}
      {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mysql-exporter.selectorLabels" . | nindent 8 }}
    spec:
      affinity: {}
      containers:
      - name: mysql-exporter
        {{- if not .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- end }}
        {{- if .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-ubi"
        {{- end }}
        args:
        - --config.my-cnf=/tmp/.my.cnf
        ports:
          - containerPort: {{ .Values.port }}
        imagePullPolicy: Always
        volumeMounts:
          - name: my-cnf
            mountPath: /tmp/.my.cnf
            subPath: .my.cnf
        {{- if .Values.sslmode }}
          - name: ssl-ca
            mountPath: /lib/cert/ca.pem
            subPath: ca.pem
          - name: ssl-key
            mountPath: /lib/cert/client-key.pem
            subPath: client-key.pem
          - name: ssl-cert
            mountPath: /lib/cert/client-cert.pem
            subPath: client-cert.pem
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
        - name: my-cnf
          secret:
            defaultMode: 420
            secretName: {{ .Values.secretName }}
            items:
              - key: .my.cnf
                path: .my.cnf
        {{- if .Values.sslmode }}
        - name: ssl-ca
          secret:
            defaultMode: 420
            secretName: {{ .Values.secretName }}
            items:
              - key: ca.pem
                path: ca.pem
        - name: ssl-key
          secret:
            defaultMode: 420
            secretName: {{ .Values.secretName }}
            items:
              - key: client-key.pem
                path: client-key.pem
        - name: ssl-cert
          secret:
            defaultMode: 420
            secretName: {{ .Values.secretName }}
            items:
              - key: client-cert.pem
                path: client-cert.pem
        {{- end }}