apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql-exporter.exporterDeploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgresql-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.exporterNamespaceName }}
      {{- include "postgresql-exporter.sysdigAnnotations" . | nindent 8 }}
      {{ else }}
      {{- include "postgresql-exporter.prometheusAnnotations" . | nindent 8 }}
      {{- end }}
      {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgresql-exporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if not .Values.ubi }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          {{- if .Values.ubi }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-ubi"
          {{- end }}   
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.port }}
          env:
            - name: DATA_SOURCE_URI
              value: {{ include "postgresql-exporter.connectionString" . }}
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName | quote }}
                  key: username
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName | quote }}
                  key: password
            - name: PG_EXPORTER_EXTEND_QUERY_PATH
              value: /tmp/queries.yaml
            - name: PG_EXPORTER_DISABLE_SETTINGS_METRICS
              value: {{ .Values.exporterParams.disableSettingsMetrics | quote }}
            - name: PG_EXPORTER_EXCLUDE_DATABASES
              value: {{ .Values.exporterParams.excludeDatabases | quote }}
            - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
              value: {{ .Values.exporterParams.autoDiscoverDatabases | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-queries
              mountPath: /tmp/queries.yaml
              subPath: queries.yaml
            {{- if .Values.dbInstance.sslRootCertEnabled }}
            - name: ssl-root-cert
              mountPath: /var/lib/postgresql/ssl-root-cert.pem
              subPath: ssl-root-cert.pem
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "postgresql-exporter.queriesName" . }}
          name: postgres-queries
        {{- if .Values.dbInstance.sslRootCertEnabled }}
        - name: ssl-root-cert
          secret:
            defaultMode: 420
            secretName: {{ .Values.secretName | quote }}
            items:
              - key: sslRootCert
                path: ssl-root-cert.pem
        {{- end }}