apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-exporter.exporterDeploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "redis-exporter.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
      {{- include "redis-exporter.sysdigAnnotations" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "redis-exporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        {{- if not .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- end }}
        {{- if .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-ubi"
        {{- end }}   
        ports:
          - containerPort: 9121
        env:
        - name: REDIS_ADDR
          value: redis://{{ .Values.url.name }}:6379
        {{- if and (.Values.auth.enabled) (.Values.auth.secretName) }}
        - name: REDIS_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.auth.secretName | quote }}
              key: user
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.auth.secretName | quote }}
              key: password
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}